# Generated by Django 5.2.15 on 2026-06-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID — set automatically on first successful payment.', max_length=50),
        ),
    ]
